# Generated by Django 3.0.8 on 2020-07-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='tag_name',
            field=models.CharField(choices=[('plan', 'Plan'), ('zone', 'Zone'), ('object', 'Object')], max_length=16),
        ),
    ]
