# Generated by Django 3.0.8 on 2020-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200713_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='client_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='client_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
